name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
    - name: Playbook
      run: ansible-playbook playbook.yml --inventory-file inventory.yml